{
  "apiVersion": "apps/v1",
  "kind": "Deployment",
  "metadata": {
    "name": "backend",
    "namespace": "civicpulse"
  },
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "name": "backend",
            "resources": {
              "requests": {
                "cpu": "163m",
                "memory": "262144k"
              }
            }
          }
        ]
      }
    }
  }
}
